# Generated by Django 2.0.7 on 2018-07-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
